# Utiliser une image de base officielle Node.js
FROM node:18

# Définir le répertoire de travail dans le container
WORKDIR /app

# Copier le fichier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du projet
COPY . .

# Exposer le port 3000 pour l'API
EXPOSE 3000

# Définir la commande de démarrage
CMD ["npm", "start"]
