 name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host:  ${{ secrets.REMOTE_HOST }}
          username: maalsi
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy application via SSH
        run: |
          ssh maalsi@${{ secrets.REMOTE_HOST }} << EOF
            cd /srv/marcel
            git pull origin main
            docker-compose up --build -d
          EOF
